contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: mailto:me@zaanposni.com
    about: Please report security vulnerabilities here.
